name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr

    - name: build sender
      run: g++ -Wall -Wextra -fprofile-arcs sender.c dataCollection.c -o sender 
      
    - name: run sender
      #run: ./testchecker
      run: ./sender
    
    - name: build receiver
      run: g++ -Wall -Wextra -fprofile-arcs receiver.c dataCollection.c -o receiver 
      
    - name: run receiver
      #run: ./testchecker
      run: ./receiver
      
    - name: build testSender
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage testCheckerSender.cpp dataCollection.c -o testchecker
      
    - name: run test
      run: ./testchecker
	  
    - name: build testReceiver
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage testCheckerReceiver.cpp dataCollection.c -o testchecker
      
    - name: Pipeline sender/receiver
      run: ./testSender | ./testReceiver
      
    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 21
